# Generated by Django 5.2.8 on 2025-12-04 09:57

import django.db.models.deletion
import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.invoice_pdf_path),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='default_payment_terms',
            field=models.TextField(blank=True, default='Payment is due within 30 days of the invoice date. Late payments may incur additional charges.', help_text='Default payment terms'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='invoice_footer',
            field=models.TextField(blank=True, help_text='Custom footer text for invoices'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='paypal_me_link',
            field=models.URLField(blank=True, help_text='Your PayPal.me link'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='stripe_payment_link',
            field=models.URLField(blank=True, help_text='Your Stripe payment link'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for no end date', null=True)),
                ('next_invoice_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('payment_link', models.URLField(blank=True)),
                ('auto_send', models.BooleanField(default=False, help_text='Automatically create invoices (manual for now)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='invoices.recurringinvoice'),
        ),
        migrations.CreateModel(
            name='RecurringInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.recurringinvoice')),
            ],
        ),
    ]
